server:
  port: 8762

amazon:
  access:
    key: AKIAQVB3RG7M2IZKEQXL
    secret-key:
  region: eu-central-1
  end-point:
    url: http://dynamodb.eu-central-1.amazonaws.com

# Set log file location and name
logging:
  file:
    name: logfile.log

springdoc:
  swagger-ui:
    url: "/openapi.yaml"
