---
openapi: 3.0.0
info:
  title: Happy Chicken API
  version: 1.0.0
  description: An API for managing daily vegan entries and challenges.
paths:
  /users:
    post:
      operationId: createUser
      summary: Create a new user using given id and name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User created successfully.
        "400":
          description: Bad request. Check your request data.
  /challenges:
    post:
      operationId: createChallenge
      summary: Create Challenge
      description: Create a new challenge.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Challenge"
      responses:
        "201":
          description: Challenge created successfully.
        "400":
          description: Bad request. Check your request data.
  "/challenges/{challengeId}":
    parameters:
      - name: challengeId
        in: path
        required: true
        description: The unique identifier of the challenge.
        schema:
          type: string
    get:
      operationId: getChallenge
      summary: Get Challenge
      description: Retrieve information about a specific challenge.
      responses:
        "200":
          description: Challenge information retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Challenge"
    delete:
      operationId: deleteChallenge
      summary: Delete Challenge
      description: Delete a specific challenge by its ID.
      responses:
        "204":
          description: Challenge deleted successfully.
        "404":
          description: Challenge not found.
  "/challenges/{challengeId}/daily-entries":
    parameters:
      - name: challengeId
        in: path
        required: true
        description: The unique identifier of the challenge.
        schema:
          type: string
    get:
      operationId: getChallengeEntriesForUser
      summary: Get Daily Entries for a Challenge
      description: Retrieve a list of daily entries for a specific challenge.
      responses:
        "200":
          description: List of daily entries for the challenge successfully retrieved.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DailyEntry"
    post:
      operationId: addDailyEntryForChallenge
      summary: Create Daily Entry for Challenge
      description: Create a new daily entry for a specific challenge.
      parameters:
        - name: challengeId
          in: path
          required: true
          description: The unique identifier of the challenge.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DailyEntry"
      responses:
        "201":
          description: Daily entry created successfully.
        "400":
          description: Bad request. Check your request data.
  "/challenges/{challengeId}/daily-entries/{entryId}":
    parameters:
      - name: challengeId
        in: path
        required: true
        description: The unique identifier of the challenge.
        schema:
          type: string
      - name: entryId
        in: path
        required: true
        description: The unique identifier of the daily entry within the challenge.
        schema:
          type: string
    put:
      operationId: updateDailyEntry
      summary: Update Daily Entry
      description: Update an existing daily entry within a challenge.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DailyEntry"
      responses:
        "200":
          description: Daily entry updated successfully.
        "400":
          description: Bad request. Check your request data.
        "404":
          description: Daily entry not found.
    delete:
      operationId: deleteDailyEntry
      summary: Delete Daily Entry
      description: Delete a specific daily entry within a challenge by its ID.
      responses:
        "204":
          description: Daily entry deleted successfully.
        "404":
          description: Daily entry not found.
components:
  schemas:
    Challenge:
      type: object
      properties:
        challenge_id:
          type: string
          format: uuid
          description: Unique identifier for the challenge.
        user_id:
          type: string
          format: uuid
        start:
          type: string
          format: date
        numberOfDays:
          type: integer
        status:
          type: string
          enum:
            - ACTIVE
            - EXPIRED
            - ENDED
        dailyEntries:
          type: array
          items:
            $ref: "#/components/schemas/DailyEntry"
      required:
        - name
        - description
    DailyEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the daily entry.
        date:
          type: string
          format: date
          description: Date of the daily entry in YYYY-MM-DD format.
        status:
          type: string
          enum:
            - GOOD
            - NEUTRAL
            - BAD
          description: The status for the daily entry.
      required:
        - date
        - status
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user.
        name:
          type: string
          description: Name of the user.
      required:
        - id
        - name